### ISSUE TITLE
model load error

### ISSUE THREAD

**Issue by PuNeal** [cosminbvb/Clothing-Pedestrian-Detection#1]
Hi, thanks for your work. I tried to load the "best.pt" to detect cloth and met such a error meassage:
```
Traceback (most recent call last):
  File "detect.py", line 184, in <module>
    detect(opt=opt)
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/bengui/code/yolov5/models/experimental.py", line 120, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "/home/bengui/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/bengui/miniconda3/envs/yolo/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```
It seems to be casued by the torch version. My torch version is 1.10.0, which one is yours when you train this model? Thank you in advance.

**Comment by cosminbvb** [comment]
Hi, try running in a new environment with the following configuration: https://raw.githubusercontent.com/ultralytics/yolov5/master/requirements.txt

**Comment by PuNeal** [comment]
Problem fixed.
